version: '3.7'

services:
  # spring boot service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - redis
      - mysql
    restart: always
  # redis service
  redis:
    container_name: gearmax_redis
    image: redis:alpine
    hostname: redis
    ports:
    - "6379:6379"
    restart: always
  # database service (mysql)
  db:
    container_name: gearmax_mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: UsedCar
      MYSQL_USER: gearmax
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    restart: always
